# Generated by Django 2.2.13 on 2021-11-12 11:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('type_here_the_type_of_content_you_want', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('What_are_you', models.CharField(choices=[('CC', 'Content creater'), ('Y', 'Youtuber')], default='CC', max_length=200)),
                ('Which_educational_or_tutorial_content_can_you_create_or_looking_for', models.CharField(choices=[('MATH', 'MATHEMATICS'), ('CS', 'COMPUTER_SCIENCE'), ('ENG', 'ENGINEERING'), ('ECON', 'ECONOMICS'), ('MED', 'MEDICINE'), ('MR', 'REVIEWING MOVIES')], default='MR', max_length=200)),
                ('terms', models.BooleanField(default=False)),
            ],
        ),
    ]
